version: '3.8'

services:
  postgresdb:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    volumes:
      #- postgres_data:/var/lib/postgresql/data  # Volumen para persistir los datos
      - ./backend/database/src:/docker-entrypoint-initdb.d  # Monta el script SQL en el directorio de inicialización
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgresdb

  api:
    build: ./backend/api
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - postgresdb

# Volúmenes definidos fuera de los servicios
#volumes:
#  postgres_data: {}  # Este volumen almacena los datos de la base de datos