name: backend
services:
  api: 
    build: api
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - DB_HOST=
      - DB_PORT=
    ports:
      - 8081:8080
  
  db: 
    build: db
    environment:
      - POSTGRES_PASSWORD=
