#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    BEGIN;
        CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
        GRANT CONNECT ON DATABASE app TO $DB_USER ;
        GRANT INSERT,SELECT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO $DB_USER;
        GRANT SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA public TO $DB_USER ;
    COMMIT;
EOSQL